# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command/command.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='command/command.proto',
  package='command',
  syntax='proto3',
  serialized_options=b'Z behnama/pkg/protomodels/analyzer',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15\x63ommand/command.proto\x12\x07\x63ommand\"\x90\x03\n\x08\x41nalyzer\x12\x10\n\x03URL\x18\x01 \x01(\tR\x03URL\x12\"\n\x0cMotionStatus\x18\x02 \x01(\x08R\x0cMotionStatus\x12\x1e\n\nMotionMode\x18\x03 \x01(\tR\nMotionMode\x12\x1e\n\nMotionSens\x18\x04 \x01(\x05R\nMotionSens\x12\x30\n\x13\x46\x61\x63\x65\x44\x65tectionStatus\x18\x05 \x01(\x08R\x13\x46\x61\x63\x65\x44\x65tectionStatus\x12,\n\x11\x46\x61\x63\x65\x44\x65tectionMode\x18\x06 \x01(\tR\x11\x46\x61\x63\x65\x44\x65tectionMode\x12\x32\n\x14\x46\x61\x63\x65\x44\x65tectionHasMask\x18\x07 \x01(\x08R\x14\x46\x61\x63\x65\x44\x65tectionHasMask\x12\x10\n\x03Key\x18\x08 \x01(\tR\x03Key\x12\x32\n\x14MotionRestrictedArea\x18\t \x01(\tR\x14MotionRestrictedArea\x12\x34\n\x15\x46\x61\x63\x65RecognitionStatus\x18\n \x01(\x08R\x15\x46\x61\x63\x65RecognitionStatusB\"Z behnama/pkg/protomodels/analyzerb\x06proto3'
)




_ANALYZER = _descriptor.Descriptor(
  name='Analyzer',
  full_name='command.Analyzer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='URL', full_name='command.Analyzer.URL', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='URL', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MotionStatus', full_name='command.Analyzer.MotionStatus', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='MotionStatus', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MotionMode', full_name='command.Analyzer.MotionMode', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='MotionMode', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MotionSens', full_name='command.Analyzer.MotionSens', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='MotionSens', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='FaceDetectionStatus', full_name='command.Analyzer.FaceDetectionStatus', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='FaceDetectionStatus', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='FaceDetectionMode', full_name='command.Analyzer.FaceDetectionMode', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='FaceDetectionMode', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='FaceDetectionHasMask', full_name='command.Analyzer.FaceDetectionHasMask', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='FaceDetectionHasMask', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Key', full_name='command.Analyzer.Key', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='Key', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MotionRestrictedArea', full_name='command.Analyzer.MotionRestrictedArea', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='MotionRestrictedArea', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='FaceRecognitionStatus', full_name='command.Analyzer.FaceRecognitionStatus', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='FaceRecognitionStatus', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=435,
)

DESCRIPTOR.message_types_by_name['Analyzer'] = _ANALYZER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Analyzer = _reflection.GeneratedProtocolMessageType('Analyzer', (_message.Message,), {
  'DESCRIPTOR' : _ANALYZER,
  '__module__' : 'command.command_pb2'
  # @@protoc_insertion_point(class_scope:command.Analyzer)
  })
_sym_db.RegisterMessage(Analyzer)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
