# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: motion.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='motion.proto',
  package='motion',
  syntax='proto3',
  serialized_options=b'Z behnama/pkg/protomodels/analyzer',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cmotion.proto\x12\x06motion\"L\n\x06Region\x12\x12\n\x04rows\x18\x01 \x01(\x05R\x04rows\x12\x18\n\x07\x63olumns\x18\x02 \x01(\x05R\x07\x63olumns\x12\x14\n\x05\x63\x65lls\x18\x03 \x01(\tR\x05\x63\x65llsB\"Z behnama/pkg/protomodels/analyzerb\x06proto3'
)




_REGION = _descriptor.Descriptor(
  name='Region',
  full_name='motion.Region',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rows', full_name='motion.Region.rows', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='rows', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='columns', full_name='motion.Region.columns', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='columns', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cells', full_name='motion.Region.cells', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='cells', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=100,
)

DESCRIPTOR.message_types_by_name['Region'] = _REGION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Region = _reflection.GeneratedProtocolMessageType('Region', (_message.Message,), {
  'DESCRIPTOR' : _REGION,
  '__module__' : 'motion_pb2'
  # @@protoc_insertion_point(class_scope:motion.Region)
  })
_sym_db.RegisterMessage(Region)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
