# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manualFace.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='manualFace.proto',
  package='media',
  syntax='proto3',
  serialized_options=b'Z\035behnama/pkg/protomodels/media',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10manualFace.proto\x12\x05media\"\x8e\x01\n\x11ManualFaceMessage\x12\"\n\x05State\x18\x01 \x01(\x0e\x32\x0c.media.StateR\x05State\x12\"\n\x05\x45rror\x18\x02 \x01(\x0e\x32\x0c.media.ErrorR\x05\x45rror\x12\x31\n\ncorrection\x18\x03 \x01(\x0e\x32\x11.media.CorrectionR\ncorrection*\"\n\x05\x45rror\x12\x06\n\x02Ok\x10\x00\x12\x11\n\rIncorrectPose\x10\x01*W\n\x05State\x12\x0b\n\x07\x46rontal\x10\x00\x12\x10\n\x0cRightProfile\x10\x01\x12\x0f\n\x0bLeftProfile\x10\x02\x12\r\n\tUpProfile\x10\x03\x12\x0f\n\x0b\x44ownProfile\x10\x04*v\n\nCorrection\x12\x0b\n\x07\x63orrect\x10\x00\x12\x06\n\x02Up\x10\x01\x12\x08\n\x04\x44own\x10\x02\x12\x08\n\x04Left\x10\x03\x12\t\n\x05Right\x10\x04\x12\n\n\x06UpLeft\x10\x05\x12\x0b\n\x07UpRight\x10\x06\x12\x0c\n\x08\x44ownLeft\x10\x07\x12\r\n\tDownRight\x10\x08\x42\x1fZ\x1d\x62\x65hnama/pkg/protomodels/mediab\x06proto3'
)

_ERROR = _descriptor.EnumDescriptor(
  name='Error',
  full_name='media.Error',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Ok', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='IncorrectPose', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=172,
  serialized_end=206,
)
_sym_db.RegisterEnumDescriptor(_ERROR)

Error = enum_type_wrapper.EnumTypeWrapper(_ERROR)
_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='media.State',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Frontal', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RightProfile', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LeftProfile', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UpProfile', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DownProfile', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=208,
  serialized_end=295,
)
_sym_db.RegisterEnumDescriptor(_STATE)

State = enum_type_wrapper.EnumTypeWrapper(_STATE)
_CORRECTION = _descriptor.EnumDescriptor(
  name='Correction',
  full_name='media.Correction',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='correct', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Up', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Down', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Left', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Right', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UpLeft', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UpRight', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DownLeft', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DownRight', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=297,
  serialized_end=415,
)
_sym_db.RegisterEnumDescriptor(_CORRECTION)

Correction = enum_type_wrapper.EnumTypeWrapper(_CORRECTION)
Ok = 0
IncorrectPose = 1
Frontal = 0
RightProfile = 1
LeftProfile = 2
UpProfile = 3
DownProfile = 4
correct = 0
Up = 1
Down = 2
Left = 3
Right = 4
UpLeft = 5
UpRight = 6
DownLeft = 7
DownRight = 8



_MANUALFACEMESSAGE = _descriptor.Descriptor(
  name='ManualFaceMessage',
  full_name='media.ManualFaceMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='State', full_name='media.ManualFaceMessage.State', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='State', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Error', full_name='media.ManualFaceMessage.Error', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='Error', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='correction', full_name='media.ManualFaceMessage.correction', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='correction', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=170,
)

_MANUALFACEMESSAGE.fields_by_name['State'].enum_type = _STATE
_MANUALFACEMESSAGE.fields_by_name['Error'].enum_type = _ERROR
_MANUALFACEMESSAGE.fields_by_name['correction'].enum_type = _CORRECTION
DESCRIPTOR.message_types_by_name['ManualFaceMessage'] = _MANUALFACEMESSAGE
DESCRIPTOR.enum_types_by_name['Error'] = _ERROR
DESCRIPTOR.enum_types_by_name['State'] = _STATE
DESCRIPTOR.enum_types_by_name['Correction'] = _CORRECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ManualFaceMessage = _reflection.GeneratedProtocolMessageType('ManualFaceMessage', (_message.Message,), {
  'DESCRIPTOR' : _MANUALFACEMESSAGE,
  '__module__' : 'manualFace_pb2'
  # @@protoc_insertion_point(class_scope:media.ManualFaceMessage)
  })
_sym_db.RegisterMessage(ManualFaceMessage)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
